#!/usr/bin/env python3
"""Emit draft/numbers.tex: one LaTeX macro per headline number, computed from output/.

Single source of truth for the paper's corpus-level numbers, so prose can never drift
from the data again. Also prints a discrepancy report against the values currently
hardcoded in the paper (as of the 2026-06-04 draft) so stale spots are easy to find.

Usage: python3 scripts/emit_paper_numbers.py   (from the repo root)
"""
import json
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "draft", "numbers.tex")

sys.path.insert(0, os.path.join(ROOT, "scripts"))
from session_roles import session_role


def fmt(n):
    """LaTeX-friendly thousands separator: 53714 -> 53{,}714."""
    return re.sub(r",", "{,}", f"{n:,}")


def main():
    metrics = {}
    for p in sorted(glob.glob(os.path.join(ROOT, "output", "metrics", "*.json"))):
        with open(p) as f:
            m = json.load(f)
        metrics[m.get("project") or os.path.basename(p)[:-5]] = m

    n_systems = len(metrics)

    loc_code = loc_raw = files_raw = 0
    cost = 0.0
    tool_calls = 0
    active_s = 0.0
    user_prompts = 0
    sessions = 0
    analyst_sessions = 0
    analyst_cost = 0.0
    tokens_total = 0
    user_turns_raw = 0
    for name, m in metrics.items():
        agg = (m.get("complexity") or {}).get("aggregate") or {}
        loc_code += agg.get("code_lines", 0)
        inv = ((m.get("inventory") or {}).get("by_lang") or {}).get("COBOL") or {}
        loc_raw += inv.get("loc", 0)
        files_raw += inv.get("files", 0)
        cost += m.get("cost_usd", 0.0)
        tool_calls += m.get("tool_calls_total", 0)
        active_s += (m.get("active_time") or {}).get("total_active_s", 0.0)
        up = m.get("user_prompts", 0)
        user_prompts += up.get("count", 0) if isinstance(up, dict) else (up or 0)
        toks = m.get("tokens") or {}
        tokens_total += sum(v for v in toks.values() if isinstance(v, (int, float)))
        for s in m.get("sessions", []):
            role = s.get("role") or session_role(s)
            if role == "analyst":
                analyst_sessions += 1
                analyst_cost += s.get("cost_usd", 0.0) or 0.0
            if role != "dev":
                continue
            sessions += 1
            user_turns_raw += s.get("user_turns", 0)

    sessions_all_path = os.path.join(ROOT, "output", "sessions_all.json")
    n_sessions_all = "?"
    if os.path.exists(sessions_all_path):
        with open(sessions_all_path) as f:
            n_sessions_all = len(json.load(f))

    active_h = active_s / 3600.0

    macros = [
        ("nSystems", str(n_systems), "systems in the corpus"),
        ("nDomains", "8", "case-study domain families (domain_coverage.md)"),
        ("nDomainsTwoAgent", "8", "domains with x2 cross-agent coverage (grid completed 2026-07-08 with cobol-pygame-cc)"),
        ("nSessionsCorpus", str(sessions), "development sessions on the corpus systems (analyst/empty excluded)"),
        ("nSessionsAnalyst", str(analyst_sessions), "post-session analyst sessions (excluded from all dev aggregates)"),
        ("corpusAnalystCostUsd", fmt(int(round(analyst_cost))), "rack-rate cost of the analyst sessions (assessment overhead)"),
        ("nSessionsAll", str(n_sessions_all), "all recorded sessions in sessions_all.json (incl. excluded projects)"),
        ("corpusCobolLocCode", fmt(loc_code), "COBOL code lines (complexity extractor, comments/blanks stripped)"),
        ("corpusCobolLocRaw", fmt(loc_raw), "COBOL raw lines (inventory: .cob/.cbl/.cpy, incl. comments/blanks)"),
        ("corpusCobolFiles", str(files_raw), "COBOL files (inventory)"),
        ("corpusCostUsd", fmt(int(round(cost))), "rack-rate upper-bound cost, USD, dev sessions only"),
        ("corpusToolCalls", fmt(tool_calls), "tool calls, dev sessions only"),
        ("corpusActiveHours", f"{active_h:.1f}", "active collaboration hours (gaps <= 10 min)"),
        ("corpusUserPrompts", str(user_prompts), "substantive user prompts (metrics user_prompts field)"),
        ("corpusUserTurnsRaw", str(user_turns_raw), "raw user turns across dev sessions"),
        ("corpusTokensTotal", fmt(tokens_total), "total tokens (in+out+cache+reasoning), dev sessions"),
        ("corpusTokensBillions", f"{tokens_total/1e9:.1f}", "total tokens, billions"),
    ]

    with open(OUT, "w") as f:
        f.write("% AUTO-GENERATED by scripts/emit_paper_numbers.py -- do not edit by hand.\n")
        f.write("% Regenerate after any change under output/ (e.g., after ingesting new sessions).\n")
        for name, val, comment in macros:
            f.write(f"\\newcommand{{\\{name}}}{{{val}}} % {comment}\n")
    print(f"wrote {OUT} ({len(macros)} macros)\n")

    # Discrepancy report vs values hardcoded in the 2026-06-04 draft
    expected = {
        "nSystems": ("14", str(n_systems)),
        "LOC (paper abstract/RQ1: 53,714 across 135 files)": ("53714/135", f"{loc_code} code | {loc_raw} raw / {files_raw} files"),
        "intro bullet (46,524 across 129 files)": ("46524/129", "stale -- replace with macros"),
        "cost (paper: $7,024 abstract vs $6,446 conclusion vs $6,115 finding 5.1)": ("7024|6446|6115", f"{cost:.0f}"),
        "sessions (paper: 26 appendix vs 27 intro vs 38 retention)": ("26|27|38", f"{sessions} corpus ({analyst_sessions} analyst) / {n_sessions_all} all"),
        "tool calls (paper: 14,845)": ("14845", str(tool_calls)),
        "active hours (paper: 78.1)": ("78.1", f"{active_h:.1f}"),
        "user prompts (paper: 392 classified)": ("392", f"{user_prompts} (metrics field; classifier count may differ)"),
    }
    print("DISCREPANCY REPORT (paper-hardcoded vs computed):")
    for k, (exp, got) in expected.items():
        print(f"  - {k}\n      paper: {exp}\n      data : {got}")


if __name__ == "__main__":
    sys.exit(main())
