#!/usr/bin/env python3
"""Generate the per-session and difficulty appendix tables from output/ into
draft/session_table.tex and draft/difficulty_table.tex, and (first run only)
replace the hand-written table environments in draft/paper.tex with \\input
lines. Re-run after any ingest; the .tex bodies are then refreshed in place."""
import json
import glob
import re
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from system_names import display

fmt = lambda n: re.sub(",", "{,}", f"{n:,}")


def human_dur(s):
    s = int(s or 0)
    d, s = divmod(s, 86400)
    h, s = divmod(s, 3600)
    m, s = divmod(s, 60)
    if d: return f"{d}d {h}h {m}m"
    if h: return f"{h}h {m}m"
    if m: return f"{m}m {s}s"
    return f"{s}s"


metrics = {}
for p in glob.glob("output/metrics/*.json"):
    m = json.load(open(p))
    metrics[m["project"]] = m
diff = json.load(open("output/difficulty.json"))

# ---------------------------------------------------------------- session table
REF_SHEET = {"in": 15.0, "out": 75.0, "cache_read": 1.5, "cache_create": 18.75}


def tok_parts(s):
    """Vendor-normalized token buckets. Fresh-in: Claude Code input_tokens
    excludes cache reads (add cache writes); Codex input_tokens includes
    cache reads (subtract them). Out: vendor output count; Codex hidden
    reasoning is a SUBSET of output_tokens (verified on the raw rollouts),
    so it is NOT added again."""
    i = s.get("input_tokens", 0) or 0
    cr = s.get("cache_read_tokens", 0) or 0
    cw = s.get("cache_creation_tokens", 0) or 0
    o = s.get("output_tokens", 0) or 0
    fresh = i + cw if s.get("agent") != "Codex" else max(i - cr, 0) + cw
    return fresh, cr, o


def ref_cost(s):
    """Cost of this session's token profile at the single reference price
    sheet (Claude Opus rack rates), isolating token volume from vendor
    pricing. Tokenizer differences across vendors remain."""
    fresh, cr, o = tok_parts(s)
    cw = s.get("cache_creation_tokens", 0) or 0
    return ((fresh - cw) * REF_SHEET["in"] + cw * REF_SHEET["cache_create"]
            + cr * REF_SHEET["cache_read"] + o * REF_SHEET["out"]) / 1e6


def tok_cols(s):
    f1 = lambda v: f"{v/1e6:,.1f}".replace(",", "{,}")
    fresh, cr, o = tok_parts(s)
    return f1(fresh), f1(cr), f1(o)


rows = []
n_excluded = 0
for proj in sorted(metrics, key=lambda p: display(p)):
    for k, s in enumerate(metrics[proj]["sessions"]):
        if (s.get("role") or "dev") != "dev":
            n_excluded += 1
            continue
        model = s.get("model")
        model_tex = f"\\texttt{{{model}}}" if model and model != "None" else "---"
        ver = s.get("version") or "---"
        cost = s.get("cost_usd") or 0.0
        fresh, cached, out = tok_cols(s)
        rows.append((proj,
                     f"\\texttt{{{display(proj)}}} & {s['agent']} & {model_tex} & {ver} & "
                     f"{human_dur(s.get('duration_s'))} & {s.get('user_turns', 0)} & "
                     f"{fmt(s.get('tool_calls_total', 0))} & "
                     f"{fresh} & {cached} & {out} & "
                     f"\\${fmt(round(cost, 2)) if cost >= 100 else f'{cost:.2f}'} \\\\"))
body = []
prev = None
for proj, line in rows:
    if prev is not None and proj != prev:
        body.append("\\midrule")
    body.append(line)
    prev = proj

session_tex = """% AUTO-GENERATED by scripts/gen_appendix_tables.py -- do not edit by hand.
\\begin{table*}[!htbp]
\\centering
\\caption{Per-session metrics for the \\nSessionsCorpus{} development
sessions across the \\nSystems{} systems. The \\nSessionsAnalyst{}
post-mortem analyst sessions and one empty log shell are excluded
from every development aggregate (Section~\\ref{sec:method}); the
analyst sessions cost \\$\\corpusAnalystCostUsd{} of assessment
overhead. Wall-clock durations include idle gaps (resumed sessions).
Token columns are vendor-normalized, in millions: fresh input
(prompt + cache writes, cache reads excluded), cached input (cache
reads), and output (hidden reasoning tokens are a subset of the
vendor's output count). Tokenizers differ across vendors, so
cross-agent token comparisons are approximate. Cost is the
rack-rate upper bound at each vendor's public per-model prices,
with cache reads billed at the reduced cache rate; tokens are the
pricing-independent view. Per-system totals are in
Table~\\ref{tab:corpus}.}
\\label{tab:appendix-sessions}
\\renewcommand{\\arraystretch}{1.08}
\\scriptsize
\\begin{tabular}{llllrrrrrrr}
\\toprule
\\textbf{Project} & \\textbf{Agent} & \\textbf{Model} & \\textbf{CLI} & \\textbf{Dur.\\ (wall)} & \\textbf{Prompts} & \\textbf{Tool calls} & \\textbf{In (M)} & \\textbf{Cache (M)} & \\textbf{Out (M)} & \\textbf{Cost (USD)} \\\\
\\midrule
""" + "\n".join(body) + """
\\bottomrule
\\end{tabular}
\\end{table*}
"""
open("draft/session_table.tex", "w").write(session_tex)
print(f"session_table.tex: {len(rows)} dev session rows ({n_excluded} analyst/empty excluded)")

# ---------------------------------------------------------------- difficulty table
drows = []
for p in sorted(diff, key=lambda p: diff[p]["index"]):
    sg = diff[p]["signals"]
    drows.append(f"\\texttt{{{display(p)}}} & {sg['active_hours']:.1f} & {sg['span_days']} & "
                 f"{sg['user_prompts']} & {sg['redirect_bug_prompts']} & "
                 f"{100*sg['error_rate']:.1f} & {sg['fix_cycles']} & "
                 f"{100*sg['fix_time_share']:.1f} & {diff[p]['index']:.2f} \\\\")
diff_tex = """% AUTO-GENERATED by scripts/gen_appendix_tables.py -- do not edit by hand.
\\begin{table}[!htbp]
\\centering
\\caption{Per-project difficulty signals (raw) and composite index
(rank-average over seven signals, 1 = lowest across the
\\nSystems{} systems).}
\\label{tab:difficulty-raw}
\\renewcommand{\\arraystretch}{1.1}
\\tiny
\\begin{tabular}{p{2.6cm}rrrrrrrr}
\\toprule
\\textbf{Project} & \\textbf{Act.\\ h} & \\textbf{Span\\ d} & \\textbf{Prompts} & \\textbf{Redir.} & \\textbf{Err\\%} & \\textbf{Fix cyc.} & \\textbf{FixSh\\%} & \\textbf{Index} \\\\
\\midrule
""" + "\n".join(drows) + """
\\bottomrule
\\end{tabular}
\\end{table}
"""
open("draft/difficulty_table.tex", "w").write(diff_tex)
print(f"difficulty_table.tex: {len(drows)} rows")


# ---------------------------------------------------------------- corpus table
crows = []
tot = dict(up=0, calls=0, fresh=0.0, cache=0.0, out=0.0, cost=0.0, refc=0.0, act=0.0, loc=0)
f1 = lambda v: f"{v/1e6:,.1f}".replace(",", "{,}")
for proj in sorted(metrics, key=lambda p: display(p)):
    m = metrics[proj]
    dev = [s for s in m["sessions"] if (s.get("role") or "dev") == "dev"]
    model = max(dev, key=lambda s: s.get("cost_usd") or 0).get("model") or "---"
    fresh = cache = out = refc = 0.0
    for s in dev:
        fr, cr, o = tok_parts(s)
        fresh += fr
        cache += cr
        out += o
        refc += ref_cost(s)
    up = m["user_prompts"]["count"]
    calls = m["tool_calls_total"]
    cost = m["cost_usd"]
    act = m["active_time"]["total_active_s"] / 3600.0
    loc = ((m.get("complexity") or {}).get("aggregate") or {}).get("code_lines", 0)
    lab = diff[proj]["label"]
    for k, v in dict(up=up, calls=calls, fresh=fresh, cache=cache, out=out,
                     cost=cost, refc=refc, act=act, loc=loc).items():
        tot[k] += v
    cost_s = f"{cost:.2f}" if cost < 10 else fmt(int(round(cost)))
    ref_s = f"{refc:.2f}" if refc < 10 else fmt(int(round(refc)))
    crows.append(f"\\texttt{{{display(proj)}}} & \\texttt{{{model}}} & {up} & "
                 f"{fmt(calls)} & {f1(fresh)} & {f1(cache)} & {f1(out)} & "
                 f"\\${cost_s} & \\${ref_s} & {act:.1f} & {fmt(loc)} & \\textsc{{{lab}}} \\\\")
total_row = (f"\\textbf{{Total ({len(crows)} systems)}} &  & \\textbf{{{tot['up']}}} & "
             f"\\textbf{{{fmt(tot['calls'])}}} & \\textbf{{{f1(tot['fresh'])}}} & "
             f"\\textbf{{{f1(tot['cache'])}}} & \\textbf{{{f1(tot['out'])}}} & "
             f"\\textbf{{\\${fmt(int(round(tot['cost'])))}}} & "
             f"\\textbf{{\\${fmt(int(round(tot['refc'])))}}} & \\textbf{{{tot['act']:.1f}}} & "
             f"\\textbf{{{fmt(tot['loc'])}}} &  \\\\")
corpus_tex = """% AUTO-GENERATED by scripts/gen_appendix_tables.py -- do not edit by hand.
\\begin{table*}[!tp]
\\centering
\\caption{Measured development profile of the \\nSystems{} systems,
grouped by domain family: dominant model, substantive user
prompts, tool calls, vendor-normalized tokens in millions (fresh
input, cache reads, output including hidden reasoning), rack-rate
cost upper bound, the cost of the same token profile at a single
reference price sheet (USD@ref, Claude Opus rack rates: 15/75 USD
per Mtok in/out, 1.5 cache reads, 18.75 cache writes), active
hours, COBOL code lines, and difficulty class. USD@ref isolates
token volume from vendor pricing (tokenizer differences across
vendors remain). The difficulty class summarizes a rank-average
index over seven observable effort signals (active hours, span,
prompts, redirects, error rate, fix cycles, fix-time share) with
per-system signals in Table~\\ref{tab:difficulty-raw} (appendix).
Development sessions only (Section~\\ref{sec:method}).
Design rationale and oracles per system are in
Table~\\ref{tab:projects}, per-session details in
Table~\\ref{tab:appendix-sessions} (appendix).}
\\label{tab:corpus}
\\renewcommand{\\arraystretch}{1.1}
\\scriptsize
\\begin{tabular}{llrrrrrrrrrl}
\\toprule
\\textbf{System} & \\textbf{Model} & \\textbf{Prompts} & \\textbf{Tool calls} & \\textbf{In (M)} & \\textbf{Cache (M)} & \\textbf{Out (M)} & \\textbf{Cost (USD)} & \\textbf{USD@ref} & \\textbf{Act.\\ h} & \\textbf{LoC} & \\textbf{Diff.} \\\\
\\midrule
""" + "\n".join(crows) + """
\\midrule
""" + total_row + """
\\bottomrule
\\end{tabular}
\\end{table*}
"""
open("draft/corpus_table.tex", "w").write(corpus_tex)
print(f"corpus_table.tex: {len(crows)} rows")

# ---------------------------------------------------------------- patch paper.tex
t = open("draft/paper.tex").read()
changed = False
if "\\input{session_table}" not in t:
    i = t.index("\\begin{table*}[!htbp]")
    assert "Per-session metrics" in t[i:i+400]
    j = t.index("\\end{table*}", i) + len("\\end{table*}")
    t = t[:i] + "\\input{session_table}" + t[j:]
    changed = True
if "\\input{difficulty_table}" not in t:
    i = t.index("\\begin{table}[!htbp]")
    assert "difficulty signals" in t[i:i+400]
    j = t.index("\\end{table}", i) + len("\\end{table}")
    t = t[:i] + "\\input{difficulty_table}" + t[j:]
    changed = True
if changed:
    open("draft/paper.tex", "w").write(t)
    print("paper.tex patched to \\input the generated tables")
else:
    print("paper.tex already uses \\input (bodies refreshed)")
